return {
  "Kurichi/review.nvim",
  dev = true,
  cmd = {
    "ReviewStart",
    "ReviewEnd",
    "ReviewResume",
    "ReviewList",
    "ReviewExport",
    "ReviewMark",
    "ReviewUnmark",
    "ReviewStatus",
  },
  keys = {
    { "<leader>vc", desc = "Add review comment" },
    { "<leader>vr", desc = "Resolve comment" },
    { "<leader>vw", desc = "Wontfix comment" },
    { "<leader>vd", desc = "Delete comment" },
    { "]r",         desc = "Next open comment" },
    { "[r",         desc = "Previous open comment" },
    { "<leader>vl", desc = "List comments" },
    { "<leader>vm", desc = "Mark file reviewed" },
    { "<leader>vt", desc = "Toggle resolved" },
  },
  opts = {
    keymaps = {
      add_comment = "<leader>vc",
      resolve = "<leader>vr",
      wontfix = "<leader>vw",
      delete = "<leader>vd",
      next_comment = "]r",
      prev_comment = "[r",
      list_comments = "<leader>vl",
      mark_file = "<leader>vm",
      toggle_resolved = "<leader>vt",
    },
  },
}
